import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header/Header";
import { cls } from "./utils/helpers";
import { poppins } from "./fonts";
import Footer from "./_components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cls(`${poppins.className} bg-white`)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
